### ISSUE TITLE
[FEATURE] add ability to add spaces to the nick

### ISSUE THREAD

**Issue by Stigstille** [Simplexity-Development/SimpleNicks#6]

**Comment by Peashooter101** [comment]
@Stigstille You did not provide any additional information for your suggestion so I have to ask:

- Did you change the regex in the configuration?
- If so, did you run into any issues?

The regex in the configuration is supposed to allow you to add spaces or other characters to the nickname.

**Comment by Stigstille** [comment]
@Peashooter101 
> - Did you change the regex in the configuration?
I did not change any regex. Let me get a screenshot from in-game when trying to add a space (give me a little bit...)

**Comment by Stigstille** [comment]
@Peashooter101 ![Screenshot_20240114-131856.png](https://github.com/Simplexity-Development/SimpleNicks/assets/134349048/a8c5bee9-d90e-4596-93bf-3109ac20af74)

**Comment by Peashooter101** [comment]
> @Peashooter101 
> > - Did you change the regex in the configuration?
> 
> I did not change any regex. Let me get a screenshot from in-game when trying to add a space (give me a little bit...)

As mentioned earlier, you will want to change the regex as that is what does the checking if the nickname is valid. If you did not change the regex, you will not be able to add spaces.

You should be able to change the regex to `[a-zA-Z0-9_ ]+` to accept spaces.

**Comment by Peashooter101** [comment]
@Stigstille 

If you did the above and are still experiencing issues, or are confused by my instructions, please join our Discord (**I highly recommend this if you are still needing support**).

Since this issue appears to be a feature that is already implemented, the issue will be closed. If there are bugs, please open a new issue.

[Simplexity Discord](https://discord.gg/qe3YQrbegA)

**Comment by Peashooter101** [comment]
You left the Discord so I figured I would let you know via a comment here.

Fixed the earlier stated problems in [v1.0.0](https://github.com/Simplexity-Development/SimpleNicks/releases/tag/1.0.0).

That was my mistake, I assumed that Minecraft automatically considered arguments within double quotes to be a single argument. Now you can add spaces n stuff without the arguments splitting.

And changing `nickname-regex` to `.*` yielded this result:
![image](https://github.com/Simplexity-Development/SimpleNicks/assets/20095065/0022e225-88ce-4888-8fd1-8a31fe0c149a)

I also resolved an issue with the plugin's config not reloading.

The plugin was updated for Paper 1.20.4.

Hope that helps! Sorry for the misunderstanding. If you have any more questions, please rejoin the Discord for additional support.
